package com.example.demo.service;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class UserService {

    private final UserRepository userRepository;

    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    /**
     * Retrieve all users.
     */
    public List<User> getAllUsers() {
        return userRepository.findAll();
    }

    /**
     * Retrieve a specific user by ID.
     */
    public Optional<User> getUserById(Long userId) {
        return userRepository.findById(userId);
    }

    /**
     * Create a new user.
     */
    public User createUser(User user) {
        user.setId(null); // Ensure ID is generated by database
        return userRepository.save(user);
    }

    /**
     * Update details of an existing user.
     */
    public Optional<User> updateUser(Long userId, User userDetails) {
        return userRepository.findById(userId).map(existingUser -> {
            existingUser.setName(userDetails.getName());
            existingUser.setUsername(userDetails.getUsername());
            existingUser.setEmail(userDetails.getEmail());
            existingUser.setPhone(userDetails.getPhone());
            existingUser.setWebsite(userDetails.getWebsite());
            return userRepository.save(existingUser);
        });
    }

    /**
     * Delete a specific user by ID.
     * @return true if deleted, false if user was not found
     */
    public boolean deleteUser(Long userId) {
        return userRepository.findById(userId).map(user -> {
            userRepository.delete(user);
            return true;
        }).orElse(false);
    }
}
